# Generated by Django 5.1.8 on 2026-05-01 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


LEVEL_MAP = {
    "Начинающие": "beginner",
    "Средний уровень": "intermediate",
    "Продвинутые": "advanced",
    "Любой уровень": "any",
}


def forwards_convert_dance_level(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.all().iterator():
        mapped = LEVEL_MAP.get(user.dance_level)
        if mapped:
            user.dance_level = mapped
            user.save(update_fields=["dance_level"])


def backwards_convert_dance_level(apps, schema_editor):
    User = apps.get_model("users", "User")
    reverse_map = {value: key for key, value in LEVEL_MAP.items()}
    for user in User.objects.all().iterator():
        mapped = reverse_map.get(user.dance_level)
        if mapped:
            user.dance_level = mapped
            user.save(update_fields=["dance_level"])


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_remove_attendance_present_attendance_status_and_more"),
        ("users", "0002_user_survey_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_dance_styles",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_time_from",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_time_to",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_weekdays",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="user",
            name="dance_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Начинающие"),
                    ("intermediate", "Средний уровень"),
                    ("advanced", "Продвинутые"),
                    ("any", "Любой уровень"),
                ],
                max_length=32,
            ),
        ),
        migrations.RunPython(forwards_convert_dance_level, backwards_convert_dance_level),
        migrations.CreateModel(
            name="UserDanceStyleSkill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Начинающие"),
                            ("intermediate", "Средний уровень"),
                            ("advanced", "Продвинутые"),
                            ("any", "Любой уровень"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "dance_style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_skills",
                        to="courses.dancestyle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dance_style_skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Навык пользователя по стилю",
                "verbose_name_plural": "Навыки пользователей по стилям",
                "db_table": "user_dance_style_skills",
                "constraints": [
                    models.UniqueConstraint(fields=("user", "dance_style"), name="unique_user_dance_style_skill")
                ],
            },
        ),
    ]
