from django.urls import path, re_path

from .views import (
    CourseEnrollAPIView,
    EnrollmentListAPIView,
    FavoriteCourseAddAPIView,
    FavoriteTeacherAddAPIView,
    LoginAPIView,
    LogoutAPIView,
    MeAPIView,
    MyCourseListAPIView,
    MyTeachingCourseListAPIView,
    NotificationDetailAPIView,
    NotificationListAPIView,
    NotificationReadAllAPIView,
    RefreshTokenAPIView,
    RegisterAPIView,
    TeacherCourseListAPIView,
    TeacherListAPIView,
    TeacherRetrieveAPIView,
    UserFlagAPIView,
    UserPreferenceAPIView,
    UserSkillAPIView,
    UserSurveyAPIView,
)

app_name = "users"

urlpatterns = [
    path("auth/register/", RegisterAPIView.as_view(), name="auth-register"),
    path("auth/login/", LoginAPIView.as_view(), name="auth-login"),
    path("auth/refresh/", RefreshTokenAPIView.as_view(), name="auth-refresh"),
    path("auth/logout/", LogoutAPIView.as_view(), name="auth-logout"),
    path("teachers/", TeacherListAPIView.as_view(), name="teacher-list"),
    path("teachers/<int:id>/", TeacherRetrieveAPIView.as_view(), name="teacher-detail"),
    path("teachers/<int:id>/courses/", TeacherCourseListAPIView.as_view(), name="teacher-course-list"),
    path("user/", MeAPIView.as_view(), name="user"),
    path("user/survey/", UserSurveyAPIView.as_view(), name="user-survey"),
    path("user/preferences/", UserPreferenceAPIView.as_view(), name="user-preferences"),
    path("user/skills/", UserSkillAPIView.as_view(), name="user-skills"),
    re_path(r"^user/flag/?$", UserFlagAPIView.as_view(), name="user-flag"),
    path("my-courses/", MyCourseListAPIView.as_view(), name="my-courses"),
    path("my-teaching-courses/", MyTeachingCourseListAPIView.as_view(), name="my-teaching-courses"),
    path("notifications/", NotificationListAPIView.as_view(), name="notification-list"),
    path("notifications/read-all/", NotificationReadAllAPIView.as_view(), name="notification-read-all"),
    path("notifications/<int:id>/", NotificationDetailAPIView.as_view(), name="notification-detail"),
    path("favorite-courses/<int:course_id>/", FavoriteCourseAddAPIView.as_view(), name="favorite-course-add"),
    path("favorite-teachers/<int:teacher_id>/", FavoriteTeacherAddAPIView.as_view(), name="favorite-teacher-add"),
    path("enrollments/", EnrollmentListAPIView.as_view(), name="enrollment-list"),
    path("courses/<int:course_id>/enroll/", CourseEnrollAPIView.as_view(), name="course-enroll"),
]
