# Generated by Django 5.1.8 on 2026-05-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Присутствовал'), ('absent', 'Отсутствовал')], default='present', max_length=16)),
                ('marked_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Отметка посещаемости',
                'verbose_name_plural': 'Отметки посещаемости',
                'db_table': 'attendance_marks',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], max_length=16)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.PositiveIntegerField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('status', models.CharField(choices=[('published', 'Опубликован'), ('active', 'Активен'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='published', max_length=16)),
                ('images', models.JSONField(blank=True, default=list)),
                ('image_cover', models.URLField(blank=True)),
                ('music_artist', models.CharField(blank=True, max_length=255)),
                ('music_track', models.CharField(blank=True, max_length=255)),
                ('music_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], max_length=3)),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('location_text', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Расписание курса',
                'verbose_name_plural': 'Расписания курсов',
                'db_table': 'course_schedule',
            },
        ),
        migrations.CreateModel(
            name='DanceStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
            options={
                'verbose_name': 'Танцевальный стиль',
                'verbose_name_plural': 'Танцевальные стили',
                'db_table': 'dance_styles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrolled_at', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Активна'), ('pending', 'Ожидает оплаты'), ('cancelled', 'Отменена'), ('completed', 'Завершена')], default='pending', max_length=16)),
                ('paid', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Запись на курс',
                'verbose_name_plural': 'Записи на курсы',
                'db_table': 'enrollments',
            },
        ),
        migrations.CreateModel(
            name='FavoriteCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Избранный курс',
                'verbose_name_plural': 'Избранные курсы',
                'db_table': 'favorite_courses',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_date', models.DateField()),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('location_text', models.CharField(blank=True, max_length=255)),
                ('hall', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('cancelled', 'Отменено')], default='scheduled', max_length=16)),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
                'db_table': 'lessons',
                'ordering': ['lesson_date', 'time_from'],
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('metro', models.CharField(blank=True, max_length=128)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('image', models.URLField(blank=True)),
                ('halls_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Студия',
                'verbose_name_plural': 'Студии',
                'db_table': 'studios',
                'ordering': ['name'],
            },
        ),
    ]
