# Generated by Django 5.1.8 on 2026-03-17 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('locations', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.teacherprofile'),
        ),
        migrations.AddField(
            model_name='courseimage',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursemusic',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='music', to='courses.course'),
        ),
        migrations.AddField(
            model_name='courseschedulerule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_rules', to='courses.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='dance_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.dancestyle'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoritecourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='courses.course'),
        ),
        migrations.AddField(
            model_name='favoritecourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseschedulerule',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_rules', to='courses.hall'),
        ),
        migrations.AddField(
            model_name='course',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.hall'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.hall'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='schedule_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.courseschedulerule'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='review',
            name='author_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews_left', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course'),
        ),
        migrations.AddField(
            model_name='studio',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studios', to='locations.city'),
        ),
        migrations.AddField(
            model_name='hall',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='courses.studio'),
        ),
        migrations.AddField(
            model_name='course',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.studio'),
        ),
        migrations.AddField(
            model_name='teacherspecialization',
            name='dance_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_specializations', to='courses.dancestyle'),
        ),
        migrations.AddField(
            model_name='teacherspecialization',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='users.teacherprofile'),
        ),
        migrations.AddField(
            model_name='userpreferreddancestyle',
            name='dance_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_by_users', to='courses.dancestyle'),
        ),
        migrations.AddField(
            model_name='userpreferreddancestyle',
            name='preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_dance_styles', to='users.userpreference'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_enrollment_per_user_and_course'),
        ),
        migrations.AddConstraint(
            model_name='favoritecourse',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_favorite_course'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('lesson', 'student'), name='unique_attendance_per_lesson_and_student'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author_user', 'course'), name='unique_course_review_per_author'),
        ),
        migrations.AddConstraint(
            model_name='hall',
            constraint=models.UniqueConstraint(fields=('studio', 'name'), name='unique_hall_name_per_studio'),
        ),
        migrations.AddConstraint(
            model_name='teacherspecialization',
            constraint=models.UniqueConstraint(fields=('teacher', 'dance_style'), name='unique_teacher_specialization'),
        ),
        migrations.AddConstraint(
            model_name='userpreferreddancestyle',
            constraint=models.UniqueConstraint(fields=('preference', 'dance_style'), name='unique_preferred_style_per_preference'),
        ),
    ]
