# Generated by Django 5.1.8 on 2026-05-01 12:54

import django.db.models.deletion
from django.db import migrations, models


LEVEL_MAP = {
    "Начинающие": "beginner",
    "Средний уровень": "intermediate",
    "Продвинутые": "advanced",
    "Любой уровень": "any",
}


def forwards_copy_attendance_and_levels(apps, schema_editor):
    Attendance = apps.get_model("courses", "Attendance")
    Course = apps.get_model("courses", "Course")

    for attendance in Attendance.objects.all().iterator():
        attendance.status = "present" if getattr(attendance, "present", False) else "absent"
        attendance.save(update_fields=["status"])

    for course in Course.objects.all().iterator():
        mapped = LEVEL_MAP.get(course.level)
        if mapped:
            course.level = mapped
            course.save(update_fields=["level"])


def backwards_copy_attendance_and_levels(apps, schema_editor):
    Attendance = apps.get_model("courses", "Attendance")
    Course = apps.get_model("courses", "Course")
    reverse_map = {value: key for key, value in LEVEL_MAP.items()}

    for attendance in Attendance.objects.all().iterator():
        attendance.present = attendance.status == "present"
        attendance.save(update_fields=["present"])

    for course in Course.objects.all().iterator():
        mapped = reverse_map.get(course.level)
        if mapped:
            course.level = mapped
            course.save(update_fields=["level"])


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("present", "Присутствовал"), ("absent", "Отсутствовал")],
                default="present",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Начинающие"),
                    ("intermediate", "Средний уровень"),
                    ("advanced", "Продвинутые"),
                    ("any", "Любой уровень"),
                ],
                max_length=32,
            ),
        ),
        migrations.RunPython(forwards_copy_attendance_and_levels, backwards_copy_attendance_and_levels),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[("present", "Присутствовал"), ("absent", "Отсутствовал")],
                default="present",
                max_length=16,
            ),
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="present",
        ),
        migrations.CreateModel(
            name="Hall",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "studio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="halls",
                        to="courses.studio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зал",
                "verbose_name_plural": "Залы",
                "db_table": "halls",
                "ordering": ["studio_id", "name"],
            },
        ),
        migrations.AddField(
            model_name="courseschedulerule",
            name="hall",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedule_rules",
                to="courses.hall",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="hall",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="courses.hall",
            ),
        ),
        migrations.AddConstraint(
            model_name="hall",
            constraint=models.UniqueConstraint(fields=("studio", "name"), name="unique_hall_name_per_studio"),
        ),
    ]
